
server:
  port: 12065
logging:
  file: ./log/order.log
  pattern:
    console: "%date{yyyy-MM-dd HH:mm:ss.SSS} -%5level [order][%15.15thread] %-40.40logger{39} [%6line]: %msg%n"
endpoints:
  cors:
    allow-credentials: true
    allowed-origins: '*'
    allowed-methods: POST,GET,DELETE,PUT
    max-age: 1800
spring:
  datasource:
      url: jdbc:mysql://deja-dt.ccf2gesv8s9h.ap-southeast-1.rds.amazonaws.com:3306/order
      password: deja_cloud
      username: deja_cloud
      tomcat:
        test-on-borrow: true
        validation-query: select 1
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  data:
    redis:
      repositories:
        enabled: false

flyway:
  url: jdbc:mysql://deja-dt.ccf2gesv8s9h.ap-southeast-1.rds.amazonaws.com:3306/order
  user: deja_cloud
  password: deja_cloud
  validate-on-migrate: true
  enabled: true
